// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Global.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from Global.proto</summary>
  public static partial class GlobalReflection {

    #region Descriptor
    /// <summary>File descriptor for Global.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GlobalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxHbG9iYWwucHJvdG8SBlByb3RvcyLAAQoHTXNnT3B0cxIMCgRmbGFnGAEg",
            "ASgNEgsKA3BpZBgCIAEoDRIMCgRycGlkGAMgASgNEg8KB3RyYW5zaWQYBCAB",
            "KAQiLgoERmxhZxIICgROb3JtEAASBwoDUlBDEAESCAoEUkVTUBACEgkKBVRS",
            "QU5TEAMiSwoLVHJhbnNUYXJnZXQSDAoIVW5kZWZpbmUQABIGCgJHQxABEgYK",
            "AkNTEAISBgoCQlMQAxIGCgJMUxAEEgYKAkRCEAUSBgoCR1MQBiI4CglHX0Fz",
            "a1BpbmcSHQoEb3B0cxgBIAEoCzIPLlByb3Rvcy5Nc2dPcHRzEgwKBHRpbWUY",
            "AiABKAMiSgoMR19Bc2tQaW5nUmV0Eh0KBG9wdHMYASABKAsyDy5Qcm90b3Mu",
            "TXNnT3B0cxINCgVzdGltZRgCIAEoAxIMCgR0aW1lGAMgASgDIsABCgZHbG9i",
            "YWwiIgoHRUNvbW1vbhILCgdTdWNjZXNzEAASCgoGRmFpbGVkEAEiHgoHQ2hh",
            "bm5lbBIHCgNXZWIQABIKCgZXWE1pbmkQASIwCghQbGF0Zm9ybRIGCgJQQxAA",
            "EgsKB0FuZHJvaWQQARIHCgNJT1MQAhIGCgJXUBADIkAKB0Jyb3dzZXISCgoG",
            "Q2hyb21lEAASCwoHRmlyZWZveBABEgoKBlNhZmFpchACEggKBEVkZ2UQAxIG",
            "CgJJRRAEIqwBCgpHX1VzZXJJbmZvEg0KBWdjTklEGAEgASgEEg4KBm9wZW5J",
            "RBgCIAEoCRIQCghuaWNrbmFtZRgDIAEoCRIOCgZhdmF0YXIYBCABKAkSDgoG",
            "Z2VuZGVyGAUgASgFEgwKBHJhbmsYBiABKAUSDQoFbW9uZXkYByABKAUSEAoI",
            "ZGlhbW9uZWQYCCABKAUSCwoDZXhwGAkgASgNEhEKCWNoYW1waW9ucxgKIAMo",
            "BSqqDQoFTXNnSUQSDAoIVW5kZWZpbmUQABIOCgplR19Bc2tQaW5nEAoSEQoN",
            "ZUdfQXNrUGluZ1JldBALEhcKEmVHQzJMU19Bc2tSZWdpc3RlchDoBxIUCg9l",
            "R0MyTFNfQXNrTG9naW4Q6QcSGQoUZUdDMkxTX0Fza1NtYXJ0TG9naW4Q6gcS",
            "FgoRZUdDMkxTX0Fza1dYTG9naW4Q6wcSGQoUZUdDMkxDX1VwZGF0ZVByb2Zp",
            "bGUQ7AcSFAoPZUdDMkdTX0Fza0xvZ2luEMwIEhUKEGVHQzJHU19LZWVwQWxp",
            "dmUQzQgSFAoPZUdDMkJTX0Fza0xvZ2luELAJEhUKEGVHQzJCU19LZWVwQWxp",
            "dmUQsQkSGwoWZUdDMkJTX1JlcXVlc3RTbmFwc2hvdBCyCRIXChJlR0MyQlNf",
            "RnJhbWVBY3Rpb24QswkSHwoaZUdDMkJTX1JlcXVlc3RGcmFtZUFjdGlvbnMQ",
            "tAkSGgoVZUdDMkJTX0NvbW1pdFNuYXBzaG90ELUJEhUKEGVHQzJCU19FbmRC",
            "YXR0bGUQtgkSFgoRZUdDMkNTX0JlZ2luTWF0Y2gQlAoSFwoSZUdDMkNTX0Nh",
            "bmNlbE1hdGNoEJUKEhgKE2VHQzJDU19RdWVyeVJhbmtpbmcQlgoSGgoVZUdD",
            "MkNTX1F1ZXJ5Q2hhbXBpb25zEJcKEhcKEmVHQzJDU19CdXlDaGFtcGlvbhCY",
            "ChISCg1lTFMyR0NfR1NJbmZvENAPEhUKEGVMUzJHQ19Bc2tSZWdSZXQQ0Q8S",
            "FwoSZUxTMkdDX0Fza0xvZ2luUmV0ENIPEhMKDmVMUzJDU19HQ0xvZ2luELQQ",
            "EhgKE2VMUzJEQl9RdWVyeUFjY291bnQQmBESFgoRZUxTMkRCX1F1ZXJ5TG9n",
            "aW4QmRESEAoLZUxTMkRCX0V4ZWMQmhESFwoSZUdTMkNTX1JlcG9ydFN0YXRl",
            "ELgXEhYKEWVHUzJDU19HQ0Fza0xvZ2luELkXEhIKDWVHUzJDU19HQ0xvc3QQ",
            "uhcSFAoPZUdTMkdDX0xvZ2luUmV0EJwYEhAKC2VHUzJHQ19LaWNrEJ0YEhIK",
            "DWVHUzJHQ19DU0xvc3QQnhgSFwoSZUJTMkNTX1JlcG9ydFN0YXRlEKAfEhkK",
            "FGVCUzJDU19CYXR0bGVJbmZvUmV0EKEfEhUKEGVCUzJDU19CYXR0bGVFbmQQ",
            "oh8SFAoPZUJTMkNTX0tpY2tVc2VyEKMfEhQKD2VCUzJHQ19Mb2dpblJldBCE",
            "IBIeChllQlMyR0NfUmVxdWVzdFNuYXBzaG90UmV0EIUgEhcKEmVCUzJHQ19G",
            "cmFtZUFjdGlvbhCGIBIiCh1lQlMyR0NfUmVxdWVzdEZyYW1lQWN0aW9uc1Jl",
            "dBCHIBIVChBlQlMyR0NfT3V0T2ZTeW5jEIggEhMKDmVDUzJMU19HU0luZm9z",
            "EIgnEhIKDWVDUzJMU19HU0luZm8QiScSEgoNZUNTMkxTX0dTTG9zdBCKJxIW",
            "ChFlQ1MyTFNfR0NMb2dpblJldBCLJxIWChFlQ1MyR1NfR0NMb2dpblJldBDs",
            "JxISCg1lQ1MyR1NfS2lja0dDEO0nEhYKEWVDUzJCU19CYXR0bGVJbmZvENAo",
            "EhgKE2VDUzJCU19CYXR0bGVFbmRSZXQQ0SgSGQoUZUNTMkdDX0JlZ2luTWF0",
            "Y2hSZXQQtCkSFgoRZUNTMkdDX01hdGNoU3RhdGUQtykSFgoRZUNTMkdDX0Fk",
            "ZFRvTWF0Y2gQuCkSGwoWZUNTMkdDX1JlbW92ZUZyb21NYXRjaBC5KRIXChJl",
            "Q1MyR0NfRW50ZXJCYXR0bGUQuikSFQoQZUNTMkdDX0JhdHRsZUVuZBC7KRIS",
            "Cg1lQ1MyR0NfQlNMb3NlELwpEhsKFmVDUzJHQ19RdWVyeVJhbmtpbmdSZXQQ",
            "vSkSHQoYZUNTMkdDX1F1ZXJ5Q2hhbXBpb25zUmV0EL4pEhoKFWVDUzJHQ19C",
            "dXlDaGFtcGlvblJldBD3JxIWChFlQ1MyREJfVXBkYXRlUmFuaxCYKhIYChNl",
            "Q1MyREJfUXVlcnlSYW5raW5nEJkqEhcKEmVDUzJEQl9CdXlDaGFtcGlvbhCa",
            "KhIbChZlREIyTFNfUXVlcnlBY2NvdW50UmV0EMA+EhkKFGVEQjJMU19RdWVy",
            "eUxvZ2luUmV0EME+EhMKDmVEQjJMU19FeGVjUmV0EMI+EhsKFmVEQjJDU19R",
            "dWVyeVJhbmtpbmdSZXQQqEYSGgoVZURCMkNTX0J1eUNoYW1waW9uUmV0EKlG",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protos.MsgID), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.MsgOpts), global::Protos.MsgOpts.Parser, new[]{ "Flag", "Pid", "Rpid", "Transid" }, null, new[]{ typeof(global::Protos.MsgOpts.Types.Flag), typeof(global::Protos.MsgOpts.Types.TransTarget) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.G_AskPing), global::Protos.G_AskPing.Parser, new[]{ "Opts", "Time" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.G_AskPingRet), global::Protos.G_AskPingRet.Parser, new[]{ "Opts", "Stime", "Time" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.Global), global::Protos.Global.Parser, null, null, new[]{ typeof(global::Protos.Global.Types.ECommon), typeof(global::Protos.Global.Types.Channel), typeof(global::Protos.Global.Types.Platform), typeof(global::Protos.Global.Types.Browser) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.G_UserInfo), global::Protos.G_UserInfo.Parser, new[]{ "GcNID", "OpenID", "Nickname", "Avatar", "Gender", "Rank", "Money", "Diamoned", "Exp", "Champions" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MsgID {
    [pbr::OriginalName("Undefine")] Undefine = 0,
    [pbr::OriginalName("eG_AskPing")] EGAskPing = 10,
    [pbr::OriginalName("eG_AskPingRet")] EGAskPingRet = 11,
    /// <summary>
    ///gc
    /// </summary>
    [pbr::OriginalName("eGC2LS_AskRegister")] EGc2LsAskRegister = 1000,
    [pbr::OriginalName("eGC2LS_AskLogin")] EGc2LsAskLogin = 1001,
    [pbr::OriginalName("eGC2LS_AskSmartLogin")] EGc2LsAskSmartLogin = 1002,
    [pbr::OriginalName("eGC2LS_AskWXLogin")] EGc2LsAskWxlogin = 1003,
    [pbr::OriginalName("eGC2LC_UpdateProfile")] EGc2LcUpdateProfile = 1004,
    [pbr::OriginalName("eGC2GS_AskLogin")] EGc2GsAskLogin = 1100,
    [pbr::OriginalName("eGC2GS_KeepAlive")] EGc2GsKeepAlive = 1101,
    [pbr::OriginalName("eGC2BS_AskLogin")] EGc2BsAskLogin = 1200,
    [pbr::OriginalName("eGC2BS_KeepAlive")] EGc2BsKeepAlive = 1201,
    [pbr::OriginalName("eGC2BS_RequestSnapshot")] EGc2BsRequestSnapshot = 1202,
    [pbr::OriginalName("eGC2BS_FrameAction")] EGc2BsFrameAction = 1203,
    [pbr::OriginalName("eGC2BS_RequestFrameActions")] EGc2BsRequestFrameActions = 1204,
    [pbr::OriginalName("eGC2BS_CommitSnapshot")] EGc2BsCommitSnapshot = 1205,
    [pbr::OriginalName("eGC2BS_EndBattle")] EGc2BsEndBattle = 1206,
    [pbr::OriginalName("eGC2CS_BeginMatch")] EGc2CsBeginMatch = 1300,
    [pbr::OriginalName("eGC2CS_CancelMatch")] EGc2CsCancelMatch = 1301,
    [pbr::OriginalName("eGC2CS_QueryRanking")] EGc2CsQueryRanking = 1302,
    [pbr::OriginalName("eGC2CS_QueryChampions")] EGc2CsQueryChampions = 1303,
    [pbr::OriginalName("eGC2CS_BuyChampion")] EGc2CsBuyChampion = 1304,
    /// <summary>
    ///ls
    /// </summary>
    [pbr::OriginalName("eLS2GC_GSInfo")] ELs2GcGsinfo = 2000,
    [pbr::OriginalName("eLS2GC_AskRegRet")] ELs2GcAskRegRet = 2001,
    [pbr::OriginalName("eLS2GC_AskLoginRet")] ELs2GcAskLoginRet = 2002,
    [pbr::OriginalName("eLS2CS_GCLogin")] ELs2CsGclogin = 2100,
    [pbr::OriginalName("eLS2DB_QueryAccount")] ELs2DbQueryAccount = 2200,
    [pbr::OriginalName("eLS2DB_QueryLogin")] ELs2DbQueryLogin = 2201,
    [pbr::OriginalName("eLS2DB_Exec")] ELs2DbExec = 2202,
    /// <summary>
    ///gs
    /// </summary>
    [pbr::OriginalName("eGS2CS_ReportState")] EGs2CsReportState = 3000,
    [pbr::OriginalName("eGS2CS_GCAskLogin")] EGs2CsGcaskLogin = 3001,
    [pbr::OriginalName("eGS2CS_GCLost")] EGs2CsGclost = 3002,
    [pbr::OriginalName("eGS2GC_LoginRet")] EGs2GcLoginRet = 3100,
    [pbr::OriginalName("eGS2GC_Kick")] EGs2GcKick = 3101,
    [pbr::OriginalName("eGS2GC_CSLost")] EGs2GcCslost = 3102,
    /// <summary>
    ///bs
    /// </summary>
    [pbr::OriginalName("eBS2CS_ReportState")] EBs2CsReportState = 4000,
    [pbr::OriginalName("eBS2CS_BattleInfoRet")] EBs2CsBattleInfoRet = 4001,
    [pbr::OriginalName("eBS2CS_BattleEnd")] EBs2CsBattleEnd = 4002,
    [pbr::OriginalName("eBS2CS_KickUser")] EBs2CsKickUser = 4003,
    [pbr::OriginalName("eBS2GC_LoginRet")] EBs2GcLoginRet = 4100,
    [pbr::OriginalName("eBS2GC_RequestSnapshotRet")] EBs2GcRequestSnapshotRet = 4101,
    [pbr::OriginalName("eBS2GC_FrameAction")] EBs2GcFrameAction = 4102,
    [pbr::OriginalName("eBS2GC_RequestFrameActionsRet")] EBs2GcRequestFrameActionsRet = 4103,
    [pbr::OriginalName("eBS2GC_OutOfSync")] EBs2GcOutOfSync = 4104,
    /// <summary>
    ///cs
    /// </summary>
    [pbr::OriginalName("eCS2LS_GSInfos")] ECs2LsGsinfos = 5000,
    [pbr::OriginalName("eCS2LS_GSInfo")] ECs2LsGsinfo = 5001,
    [pbr::OriginalName("eCS2LS_GSLost")] ECs2LsGslost = 5002,
    [pbr::OriginalName("eCS2LS_GCLoginRet")] ECs2LsGcloginRet = 5003,
    [pbr::OriginalName("eCS2GS_GCLoginRet")] ECs2GsGcloginRet = 5100,
    [pbr::OriginalName("eCS2GS_KickGC")] ECs2GsKickGc = 5101,
    [pbr::OriginalName("eCS2BS_BattleInfo")] ECs2BsBattleInfo = 5200,
    [pbr::OriginalName("eCS2BS_BattleEndRet")] ECs2BsBattleEndRet = 5201,
    [pbr::OriginalName("eCS2GC_BeginMatchRet")] ECs2GcBeginMatchRet = 5300,
    [pbr::OriginalName("eCS2GC_MatchState")] ECs2GcMatchState = 5303,
    [pbr::OriginalName("eCS2GC_AddToMatch")] ECs2GcAddToMatch = 5304,
    [pbr::OriginalName("eCS2GC_RemoveFromMatch")] ECs2GcRemoveFromMatch = 5305,
    [pbr::OriginalName("eCS2GC_EnterBattle")] ECs2GcEnterBattle = 5306,
    [pbr::OriginalName("eCS2GC_BattleEnd")] ECs2GcBattleEnd = 5307,
    [pbr::OriginalName("eCS2GC_BSLose")] ECs2GcBslose = 5308,
    [pbr::OriginalName("eCS2GC_QueryRankingRet")] ECs2GcQueryRankingRet = 5309,
    [pbr::OriginalName("eCS2GC_QueryChampionsRet")] ECs2GcQueryChampionsRet = 5310,
    [pbr::OriginalName("eCS2GC_BuyChampionRet")] ECs2GcBuyChampionRet = 5111,
    [pbr::OriginalName("eCS2DB_UpdateRank")] ECs2DbUpdateRank = 5400,
    [pbr::OriginalName("eCS2DB_QueryRanking")] ECs2DbQueryRanking = 5401,
    [pbr::OriginalName("eCS2DB_BuyChampion")] ECs2DbBuyChampion = 5402,
    /// <summary>
    ///db
    /// </summary>
    [pbr::OriginalName("eDB2LS_QueryAccountRet")] EDb2LsQueryAccountRet = 8000,
    [pbr::OriginalName("eDB2LS_QueryLoginRet")] EDb2LsQueryLoginRet = 8001,
    [pbr::OriginalName("eDB2LS_ExecRet")] EDb2LsExecRet = 8002,
    [pbr::OriginalName("eDB2CS_QueryRankingRet")] EDb2CsQueryRankingRet = 9000,
    [pbr::OriginalName("eDB2CS_BuyChampionRet")] EDb2CsBuyChampionRet = 9001,
  }

  #endregion

  #region Messages
  public sealed partial class MsgOpts : pb::IMessage<MsgOpts> {
    private static readonly pb::MessageParser<MsgOpts> _parser = new pb::MessageParser<MsgOpts>(() => new MsgOpts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgOpts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GlobalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOpts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOpts(MsgOpts other) : this() {
      flag_ = other.flag_;
      pid_ = other.pid_;
      rpid_ = other.rpid_;
      transid_ = other.transid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOpts Clone() {
      return new MsgOpts(this);
    }

    /// <summary>Field number for the "flag" field.</summary>
    public const int FlagFieldNumber = 1;
    private uint flag_;
    /// <summary>
    ///protobuf是变长编码的,数值在0-127就只会用占用一个byte
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Flag {
      get { return flag_; }
      set {
        flag_ = value;
      }
    }

    /// <summary>Field number for the "pid" field.</summary>
    public const int PidFieldNumber = 2;
    private uint pid_;
    /// <summary>
    ///运行时消息pid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Pid {
      get { return pid_; }
      set {
        pid_ = value;
      }
    }

    /// <summary>Field number for the "rpid" field.</summary>
    public const int RpidFieldNumber = 3;
    private uint rpid_;
    /// <summary>
    ///回应对应请求的消息的pid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Rpid {
      get { return rpid_; }
      set {
        rpid_ = value;
      }
    }

    /// <summary>Field number for the "transid" field.</summary>
    public const int TransidFieldNumber = 4;
    private ulong transid_;
    /// <summary>
    ///转发的网络id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Transid {
      get { return transid_; }
      set {
        transid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgOpts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgOpts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Flag != other.Flag) return false;
      if (Pid != other.Pid) return false;
      if (Rpid != other.Rpid) return false;
      if (Transid != other.Transid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Flag != 0) hash ^= Flag.GetHashCode();
      if (Pid != 0) hash ^= Pid.GetHashCode();
      if (Rpid != 0) hash ^= Rpid.GetHashCode();
      if (Transid != 0UL) hash ^= Transid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Flag != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Flag);
      }
      if (Pid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Pid);
      }
      if (Rpid != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Rpid);
      }
      if (Transid != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Transid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Flag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Flag);
      }
      if (Pid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Pid);
      }
      if (Rpid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rpid);
      }
      if (Transid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Transid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgOpts other) {
      if (other == null) {
        return;
      }
      if (other.Flag != 0) {
        Flag = other.Flag;
      }
      if (other.Pid != 0) {
        Pid = other.Pid;
      }
      if (other.Rpid != 0) {
        Rpid = other.Rpid;
      }
      if (other.Transid != 0UL) {
        Transid = other.Transid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Flag = input.ReadUInt32();
            break;
          }
          case 16: {
            Pid = input.ReadUInt32();
            break;
          }
          case 24: {
            Rpid = input.ReadUInt32();
            break;
          }
          case 32: {
            Transid = input.ReadUInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the MsgOpts message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Flag {
        [pbr::OriginalName("Norm")] Norm = 0,
        [pbr::OriginalName("RPC")] Rpc = 1,
        [pbr::OriginalName("RESP")] Resp = 2,
        [pbr::OriginalName("TRANS")] Trans = 3,
      }

      public enum TransTarget {
        [pbr::OriginalName("Undefine")] Undefine = 0,
        [pbr::OriginalName("GC")] Gc = 1,
        [pbr::OriginalName("CS")] Cs = 2,
        [pbr::OriginalName("BS")] Bs = 3,
        [pbr::OriginalName("LS")] Ls = 4,
        [pbr::OriginalName("DB")] Db = 5,
        [pbr::OriginalName("GS")] Gs = 6,
      }

    }
    #endregion

  }

  public sealed partial class G_AskPing : pb::IMessage<G_AskPing> {
    private static readonly pb::MessageParser<G_AskPing> _parser = new pb::MessageParser<G_AskPing>(() => new G_AskPing());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<G_AskPing> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GlobalReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_AskPing() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_AskPing(G_AskPing other) : this() {
      opts_ = other.opts_ != null ? other.opts_.Clone() : null;
      time_ = other.time_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_AskPing Clone() {
      return new G_AskPing(this);
    }

    /// <summary>Field number for the "opts" field.</summary>
    public const int OptsFieldNumber = 1;
    private global::Protos.MsgOpts opts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.MsgOpts Opts {
      get { return opts_; }
      set {
        opts_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as G_AskPing);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(G_AskPing other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Opts, other.Opts)) return false;
      if (Time != other.Time) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (opts_ != null) hash ^= Opts.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (opts_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Opts);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (opts_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Opts);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(G_AskPing other) {
      if (other == null) {
        return;
      }
      if (other.opts_ != null) {
        if (opts_ == null) {
          opts_ = new global::Protos.MsgOpts();
        }
        Opts.MergeFrom(other.Opts);
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (opts_ == null) {
              opts_ = new global::Protos.MsgOpts();
            }
            input.ReadMessage(opts_);
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class G_AskPingRet : pb::IMessage<G_AskPingRet> {
    private static readonly pb::MessageParser<G_AskPingRet> _parser = new pb::MessageParser<G_AskPingRet>(() => new G_AskPingRet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<G_AskPingRet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GlobalReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_AskPingRet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_AskPingRet(G_AskPingRet other) : this() {
      opts_ = other.opts_ != null ? other.opts_.Clone() : null;
      stime_ = other.stime_;
      time_ = other.time_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_AskPingRet Clone() {
      return new G_AskPingRet(this);
    }

    /// <summary>Field number for the "opts" field.</summary>
    public const int OptsFieldNumber = 1;
    private global::Protos.MsgOpts opts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.MsgOpts Opts {
      get { return opts_; }
      set {
        opts_ = value;
      }
    }

    /// <summary>Field number for the "stime" field.</summary>
    public const int StimeFieldNumber = 2;
    private long stime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Stime {
      get { return stime_; }
      set {
        stime_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 3;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as G_AskPingRet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(G_AskPingRet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Opts, other.Opts)) return false;
      if (Stime != other.Stime) return false;
      if (Time != other.Time) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (opts_ != null) hash ^= Opts.GetHashCode();
      if (Stime != 0L) hash ^= Stime.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (opts_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Opts);
      }
      if (Stime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Stime);
      }
      if (Time != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (opts_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Opts);
      }
      if (Stime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Stime);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(G_AskPingRet other) {
      if (other == null) {
        return;
      }
      if (other.opts_ != null) {
        if (opts_ == null) {
          opts_ = new global::Protos.MsgOpts();
        }
        Opts.MergeFrom(other.Opts);
      }
      if (other.Stime != 0L) {
        Stime = other.Stime;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (opts_ == null) {
              opts_ = new global::Protos.MsgOpts();
            }
            input.ReadMessage(opts_);
            break;
          }
          case 16: {
            Stime = input.ReadInt64();
            break;
          }
          case 24: {
            Time = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Global : pb::IMessage<Global> {
    private static readonly pb::MessageParser<Global> _parser = new pb::MessageParser<Global>(() => new Global());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Global> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GlobalReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Global() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Global(Global other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Global Clone() {
      return new Global(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Global);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Global other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Global other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Global message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ECommon {
        [pbr::OriginalName("Success")] Success = 0,
        [pbr::OriginalName("Failed")] Failed = 1,
      }

      public enum Channel {
        [pbr::OriginalName("Web")] Web = 0,
        [pbr::OriginalName("WXMini")] Wxmini = 1,
      }

      public enum Platform {
        [pbr::OriginalName("PC")] Pc = 0,
        [pbr::OriginalName("Android")] Android = 1,
        [pbr::OriginalName("IOS")] Ios = 2,
        [pbr::OriginalName("WP")] Wp = 3,
      }

      public enum Browser {
        [pbr::OriginalName("Chrome")] Chrome = 0,
        [pbr::OriginalName("Firefox")] Firefox = 1,
        [pbr::OriginalName("Safair")] Safair = 2,
        [pbr::OriginalName("Edge")] Edge = 3,
        [pbr::OriginalName("IE")] Ie = 4,
      }

    }
    #endregion

  }

  public sealed partial class G_UserInfo : pb::IMessage<G_UserInfo> {
    private static readonly pb::MessageParser<G_UserInfo> _parser = new pb::MessageParser<G_UserInfo>(() => new G_UserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<G_UserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GlobalReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_UserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_UserInfo(G_UserInfo other) : this() {
      gcNID_ = other.gcNID_;
      openID_ = other.openID_;
      nickname_ = other.nickname_;
      avatar_ = other.avatar_;
      gender_ = other.gender_;
      rank_ = other.rank_;
      money_ = other.money_;
      diamoned_ = other.diamoned_;
      exp_ = other.exp_;
      champions_ = other.champions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public G_UserInfo Clone() {
      return new G_UserInfo(this);
    }

    /// <summary>Field number for the "gcNID" field.</summary>
    public const int GcNIDFieldNumber = 1;
    private ulong gcNID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong GcNID {
      get { return gcNID_; }
      set {
        gcNID_ = value;
      }
    }

    /// <summary>Field number for the "openID" field.</summary>
    public const int OpenIDFieldNumber = 2;
    private string openID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OpenID {
      get { return openID_; }
      set {
        openID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickname" field.</summary>
    public const int NicknameFieldNumber = 3;
    private string nickname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nickname {
      get { return nickname_; }
      set {
        nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 4;
    private string avatar_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Avatar {
      get { return avatar_; }
      set {
        avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 5;
    private int gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 6;
    private int rank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "money" field.</summary>
    public const int MoneyFieldNumber = 7;
    private int money_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Money {
      get { return money_; }
      set {
        money_ = value;
      }
    }

    /// <summary>Field number for the "diamoned" field.</summary>
    public const int DiamonedFieldNumber = 8;
    private int diamoned_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Diamoned {
      get { return diamoned_; }
      set {
        diamoned_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 9;
    private uint exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "champions" field.</summary>
    public const int ChampionsFieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_champions_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> champions_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Champions {
      get { return champions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as G_UserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(G_UserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GcNID != other.GcNID) return false;
      if (OpenID != other.OpenID) return false;
      if (Nickname != other.Nickname) return false;
      if (Avatar != other.Avatar) return false;
      if (Gender != other.Gender) return false;
      if (Rank != other.Rank) return false;
      if (Money != other.Money) return false;
      if (Diamoned != other.Diamoned) return false;
      if (Exp != other.Exp) return false;
      if(!champions_.Equals(other.champions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GcNID != 0UL) hash ^= GcNID.GetHashCode();
      if (OpenID.Length != 0) hash ^= OpenID.GetHashCode();
      if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
      if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
      if (Gender != 0) hash ^= Gender.GetHashCode();
      if (Rank != 0) hash ^= Rank.GetHashCode();
      if (Money != 0) hash ^= Money.GetHashCode();
      if (Diamoned != 0) hash ^= Diamoned.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      hash ^= champions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GcNID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(GcNID);
      }
      if (OpenID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OpenID);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nickname);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Avatar);
      }
      if (Gender != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Gender);
      }
      if (Rank != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Rank);
      }
      if (Money != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Money);
      }
      if (Diamoned != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Diamoned);
      }
      if (Exp != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Exp);
      }
      champions_.WriteTo(output, _repeated_champions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GcNID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GcNID);
      }
      if (OpenID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpenID);
      }
      if (Nickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
      }
      if (Avatar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
      }
      if (Gender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
      }
      if (Rank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rank);
      }
      if (Money != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Money);
      }
      if (Diamoned != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diamoned);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      size += champions_.CalculateSize(_repeated_champions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(G_UserInfo other) {
      if (other == null) {
        return;
      }
      if (other.GcNID != 0UL) {
        GcNID = other.GcNID;
      }
      if (other.OpenID.Length != 0) {
        OpenID = other.OpenID;
      }
      if (other.Nickname.Length != 0) {
        Nickname = other.Nickname;
      }
      if (other.Avatar.Length != 0) {
        Avatar = other.Avatar;
      }
      if (other.Gender != 0) {
        Gender = other.Gender;
      }
      if (other.Rank != 0) {
        Rank = other.Rank;
      }
      if (other.Money != 0) {
        Money = other.Money;
      }
      if (other.Diamoned != 0) {
        Diamoned = other.Diamoned;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      champions_.Add(other.champions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GcNID = input.ReadUInt64();
            break;
          }
          case 18: {
            OpenID = input.ReadString();
            break;
          }
          case 26: {
            Nickname = input.ReadString();
            break;
          }
          case 34: {
            Avatar = input.ReadString();
            break;
          }
          case 40: {
            Gender = input.ReadInt32();
            break;
          }
          case 48: {
            Rank = input.ReadInt32();
            break;
          }
          case 56: {
            Money = input.ReadInt32();
            break;
          }
          case 64: {
            Diamoned = input.ReadInt32();
            break;
          }
          case 72: {
            Exp = input.ReadUInt32();
            break;
          }
          case 82:
          case 80: {
            champions_.AddEntriesFrom(input, _repeated_champions_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
