export class Consts {
}
Consts.SCREEN_WIDTH = 1280;
Consts.SCREEN_HEIGHT = 720;
Consts.FRAME_ACTION_SEND_INTERVAL = 60;
Consts.ASSETS_MAP_PREFIX = "m";
Consts.ASSETS_MODEL_PREFIX = "m";
Consts.ASSETS_ENTITY_PREFIX = "e";
Consts.ASSETS_SKILL_PREFIX = "s";
Consts.ASSETS_EMITTER_PREFIX = "m";
Consts.ASSETS_BULLET_PREFIX = "b";
Consts.ASSETS_SCENE_ITEM_PREFIX = "s";
Consts.ASSETS_EFFECT_PREFIX = "fx";
Consts.LOGIC_TO_PIXEL_RATIO = 100;
Consts.RANK_STEP = 400;
Consts.RANK_START = 1200;
