export var EAttr;
(function (EAttr) {
    EAttr[EAttr["MHP"] = 0] = "MHP";
    EAttr[EAttr["HP"] = 1] = "HP";
    EAttr[EAttr["MMP"] = 2] = "MMP";
    EAttr[EAttr["MP"] = 3] = "MP";
    EAttr[EAttr["MP_RECOVER"] = 4] = "MP_RECOVER";
    EAttr[EAttr["ATK"] = 5] = "ATK";
    EAttr[EAttr["DEF"] = 6] = "DEF";
    EAttr[EAttr["MOVE_DIRECTION"] = 7] = "MOVE_DIRECTION";
    EAttr[EAttr["VELOCITY"] = 8] = "VELOCITY";
    EAttr[EAttr["GLADIATOR_TIME"] = 9] = "GLADIATOR_TIME";
    EAttr[EAttr["S_DISABLE_MOVE"] = 500] = "S_DISABLE_MOVE";
    EAttr[EAttr["S_DISABLE_TURN"] = 501] = "S_DISABLE_TURN";
    EAttr[EAttr["S_DISABLE_SKILL"] = 502] = "S_DISABLE_SKILL";
    EAttr[EAttr["S_DISABLE_COLLISION"] = 503] = "S_DISABLE_COLLISION";
    EAttr[EAttr["S_SUPPER_ARMOR"] = 550] = "S_SUPPER_ARMOR";
    EAttr[EAttr["S_INVULNER_ABILITY"] = 551] = "S_INVULNER_ABILITY";
    EAttr[EAttr["S_HP_ADD"] = 600] = "S_HP_ADD";
    EAttr[EAttr["S_MP_ADD"] = 601] = "S_MP_ADD";
    EAttr[EAttr["S_ATK_ADD"] = 602] = "S_ATK_ADD";
    EAttr[EAttr["S_DEF_ADD"] = 603] = "S_DEF_ADD";
    EAttr[EAttr["S_SPEED_ADD"] = 604] = "S_SPEED_ADD";
})(EAttr || (EAttr = {}));
